directories:
  "db/migrate":
    FeatureEnvy:
      enabled: false
    IrresponsibleModule:
      enabled: false
    UncommunicativeVariableName:
      enabled: false
exclude_paths:
  - bundle
  - .bundle
